In [3]:
import requests
year = 2022
day = 12
url = f"https://adventofcode.com/{year}/day/{day}/input"

with open('cookie.txt', 'r') as file:
    session = file.read()

headers = {'cookie': f"session={session}"}

with open(f'day_{day}_input.txt', 'wb') as file:
    file.write(requests.get(url, headers=headers).content)

In [5]:
import os
if os.path.exists(f"day_{day}_test.txt"):
    test = [x.strip() for x in open(f'day_{day}_test.txt', 'r')]
    for line in test[:10]:
        print(line.strip())
print("---")
if os.path.exists(f"day_{day}_test_2.txt"):
    test_2 = [x.strip() for x in open(f'day_{day}_test_2.txt', 'r')]
    for line in test[:10]:
        print(line.strip())
print("---")
lines = [x.strip() for x in open(f'day_{day}_input.txt', 'r')]
for line in lines[:10]:
    print(line.strip())

Sabqponm
abcryxxl
accszExk
acctuvwj
abdefghi
---
---
abccccccaaccaaccccaaaaacccccaaaaccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaccccccccccccccccaaaccccccccccccaacccccccccccccccccccccccccccccccccccccccccaaaa
abaaaaccaaaaaccccaaaaaccccccaaaaccccccccccccccccccccaaacccccccccccaaaaaaaaaaaaaaaaaaccccccccccccccccaaaaccccccaaacaaccccccccccccccccccccccccccccccccccccccccaaaaa
abaaacccaaaaaaaacaaaaaacccccaaaaccccccccccccccccccccaaaaacccccccccaaaaaaaaaaaaaaaaacccccccccaaccccaaaaaacccccccaaaaaccccaaccccccccccccccacccccccccccccccccccaaaaa
abaaacccccaaaaaccccaaaaccccccaaacccccccccccccccccccaaaaaccccccccccaaaaaacacaaaaaacccccccccccaaccccaaaaacccccccccaaaaaaccaaaaaaccccccccccaaaccccacccccccccccaaaaaa
abaacccccaaaaaccccaacccccccccccccccaaaaacccccccccccaaaaacccccccccaaaaaaaaccaaaaaaacccccccaaaaaaaaccaaaaacccccccaaaaaaaccaaaaacccccccccccaaacccaaaccccccccccccccaa
abaaacccaaacaacccccccccccccccccccccaaaaaccccccccccccaaaaacccccccaaaaaaaaaccaaccaaacccccccaaaaaaaaccaacccccccccaaaaaaccaaaaaacccccccccccca

In [161]:
import numpy as np

case = test

map_ = np.zeros(dtype='str',shape=(len(case),len(case[0])))
for i, row in enumerate(case):
    for j, col in enumerate(row):
        map_[i][j] = col
        
print(map_)
itemindex = np.where(map_ == 'S')
col_S = itemindex[0][0]
row_S = itemindex[1][0]


def within_one(row,col,this):
    res = ord(map_[col][row]) == ord(this) or ord(map_[col][row]) == ord(this) + 1 or this == 'S' or this =='z' and map_[col][row] == 'E'
    return res

best_to_here = np.zeros(shape=map_.shape) + map_.shape[0]*map_.shape[1]
paths = []

def take_step(path_so_far,row,col):
    this = map_[col][row]
    if (row,col,this) in path_so_far:
        return False
    if len(path_so_far) + 1 < best_to_here[col][row]:
        best_to_here[col][row] = len(path_so_far) + 1
    else:
        return False
    next_step = path_so_far.copy()
    next_step.append((row,col,this))
    # if len(next_step) > 500:
    #     return False
    if map_[col][row] == 'E':
        paths.append(next_step)
        print(len(next_step),next_step)
        return True
    if row < map_.shape[1] - 1 :
        if within_one(row+1,col,this):
            take_step(next_step, row+1,col)
    if row - 1 >= 0:
        if within_one(row-1,col,this):
            take_step(next_step, row-1,col)
    if col < map_.shape[0] -1: 
        if within_one(row,col+1,this):
            take_step(next_step, row,col+1)
    if col-1 >= 0:
        if within_one(row,col-1,this):
            take_step(next_step, row,col-1)
    

take_step([],row_S,col_S)
print([len(path) for path in paths])

[['S' 'a' 'b' 'q' 'p' 'o' 'n' 'm']
 ['a' 'b' 'c' 'r' 'y' 'x' 'x' 'l']
 ['a' 'c' 'c' 's' 'z' 'E' 'x' 'k']
 ['a' 'c' 'c' 't' 'u' 'v' 'w' 'j']
 ['a' 'b' 'd' 'e' 'f' 'g' 'h' 'i']]
34 [(0, 0, 'S'), (1, 0, 'a'), (2, 0, 'b'), (2, 1, 'c'), (2, 2, 'c'), (1, 2, 'c'), (1, 3, 'c'), (2, 3, 'c'), (2, 4, 'd'), (3, 4, 'e'), (4, 4, 'f'), (5, 4, 'g'), (6, 4, 'h'), (7, 4, 'i'), (7, 3, 'j'), (7, 2, 'k'), (7, 1, 'l'), (7, 0, 'm'), (6, 0, 'n'), (5, 0, 'o'), (4, 0, 'p'), (3, 0, 'q'), (3, 1, 'r'), (3, 2, 's'), (3, 3, 't'), (4, 3, 'u'), (5, 3, 'v'), (6, 3, 'w'), (6, 2, 'x'), (6, 1, 'x'), (5, 1, 'x'), (4, 1, 'y'), (4, 2, 'z'), (5, 2, 'E')]
32 [(0, 0, 'S'), (1, 0, 'a'), (2, 0, 'b'), (2, 1, 'c'), (2, 2, 'c'), (2, 3, 'c'), (2, 4, 'd'), (3, 4, 'e'), (4, 4, 'f'), (5, 4, 'g'), (6, 4, 'h'), (7, 4, 'i'), (7, 3, 'j'), (7, 2, 'k'), (7, 1, 'l'), (7, 0, 'm'), (6, 0, 'n'), (5, 0, 'o'), (4, 0, 'p'), (3, 0, 'q'), (3, 1, 'r'), (3, 2, 's'), (3, 3, 't'), (4, 3, 'u'), (5, 3, 'v'), (6, 3, 'w'), (6, 2, 'x'), (6, 1, 'x'), (5, 1, 'x'

In [223]:

#BACKWARDS 

import numpy as np

case = lines

map_ = np.zeros(dtype='str',shape=(len(case),len(case[0])))
for i, row in enumerate(case):
    for j, col in enumerate(row):
        map_[i][j] = col
        
print(map_)
itemindex = np.where(map_ == 'E')
col_S = itemindex[0][0]
row_S = itemindex[1][0]

def within_one(row,col,this):
    res = ord(map_[col][row]) == ord(this) or ord(map_[col][row]) == ord(this) - 1 or this == 'E' or (this =='a' and map_[col][row] == 'S')
    return res

best_to_here = np.zeros(shape=map_.shape) + map_.shape[0]*map_.shape[1]
paths = []

def take_step(path_so_far,row,col):
    this = map_[col][row]
    if (row,col,this) in path_so_far:
        return False
    if len(path_so_far) + 1 < best_to_here[col][row]:
#        print(len(path_so_far) + 1)
        best_to_here[col][row] = len(path_so_far) + 1
    else:
        return False
    next_step = path_so_far.copy()
    next_step.append((row,col,this))
    if len(next_step) > 500:
        return False
    if map_[col][row] == 'S':
        paths.append(next_step)
        print(len(next_step),next_step)
        return True
    if row < map_.shape[1] - 1 :
        if within_one(row+1,col,this):
            take_step(next_step, row+1,col)
    if row - 1 >= 0:
        if within_one(row-1,col,this):
            take_step(next_step, row-1,col)
    if col < map_.shape[0] -1: 
        if within_one(row,col+1,this):
            take_step(next_step, row,col+1)
    if col-1 >= 0:
        if within_one(row,col-1,this):
            take_step(next_step, row,col-1)
    

take_step([],row_S,col_S)
#print([len(path) for path in paths])
print(best_to_here)
print(col_S)
print(row_S)
print(best_to_here.shape)
for i, col in enumerate(best_to_here):
    for j, row in enumerate(col):
        pass
    if i in range(col_S-5,col_S+5):
        print(col[row_S-5:row_S+5])

[['a' 'b' 'c' ... 'a' 'a' 'a']
 ['a' 'b' 'a' ... 'a' 'a' 'a']
 ['a' 'b' 'a' ... 'a' 'a' 'a']
 ...
 ['a' 'b' 'c' ... 'a' 'a' 'a']
 ['a' 'b' 'c' ... 'a' 'a' 'a']
 ['a' 'b' 'c' ... 'a' 'a' 'a']]
[[6601. 6601. 6601. ... 6601. 6601. 6601.]
 [6601. 6601. 6601. ... 6601. 6601. 6601.]
 [6601. 6601. 6601. ... 6601. 6601. 6601.]
 ...
 [6601. 6601. 6601. ... 6601. 6601. 6601.]
 [6601. 6601. 6601. ... 6601. 6601. 6601.]
 [6601. 6601. 6601. ... 6601. 6601. 6601.]]
20
138
(41, 161)
[47. 46. 45. 44. 43. 42.  7.  8.  9. 34.]
[48. 47. 46. 45. 44. 43.  6.  7.  8.  9.]
[49.  8.  7.  6.  5.  4.  5.  6.  7. 32.]
[ 8.  7.  6.  5.  4.  3.  4.  5.  6. 31.]
[53.  6.  5.  4.  3.  2.  3.  4.  5.  6.]
[54.  5.  4.  3.  2.  1.  2.  3.  4.  5.]
[55. 56.  5.  4.  3.  2.  3.  4.  5.  6.]
[56. 57.  6.  5.  4.  3.  4.  5.  6.  7.]
[57.  8.  7.  6.  5.  4.  5.  6.  7.  8.]
[58.  9.  8.  7.  6. 11. 12.  7.  8.  9.]
